name: Sync Releases

on:
  #schedule:
  #  - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Releases
        shell: pwsh
        run: |
          scripts/Delivery.Main.ps1 `
            -organisation "${{ vars.ORGANISATION }}" `
            -project "${{ vars.PROJECT }}" `
            -mappingsFile "${{ github.workspace }}/scripts/teamMappings.json" `
            -releaseDateField "${{ vars.RELEASE_DATE_FIELD }}" `
            -releaseWit "${{ vars.RELEASE_WIT }}" `
            -businessJustificationField "${{ vars.BUSINESS_JUSTIFICATION_FIELD }}" `
            -ticketingSystemBaseUrl "${{ vars.TICKETING_SYSTEM_BASE_URL }}"
        env:
          ACCESS_TOKEN: ${{ secrets.ADO_PAT }}
